CREATE TABLE IF NOT EXISTS a_modern (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    record_id   INT UNSIGNED          NOT NULL COMMENT 'Parent form / survey record',
    indicator   VARCHAR(500)          NOT NULL COMMENT 'Row label / indicator name',
    current_begin_10_14		DECIMAL(15,2)         DEFAULT NULL,
    current_begin_15_19   	DECIMAL(15,2)         DEFAULT NULL,
    current_begin_20_49   	DECIMAL(15,2)         DEFAULT NULL,
    current_begin_total     DECIMAL(15,2)         DEFAULT NULL,
    new_prev_10_14			DECIMAL(15,2)         DEFAULT NULL,
    new_prev_15_19   		DECIMAL(15,2)         DEFAULT NULL,
    new_prev_20_49   		DECIMAL(15,2)         DEFAULT NULL,
    new_prev_total     		DECIMAL(15,2)         DEFAULT NULL,
    other_acceptors_10_14	DECIMAL(15,2)         DEFAULT NULL,
    other_acceptors_15_19   DECIMAL(15,2)         DEFAULT NULL,
    other_acceptors_20_49   DECIMAL(15,2)         DEFAULT NULL,
    other_acceptors_total   DECIMAL(15,2)         DEFAULT NULL,
    drop_10_14				DECIMAL(15,2)         DEFAULT NULL,
    drop_15_19   			DECIMAL(15,2)         DEFAULT NULL,
    drop_20_49   			DECIMAL(15,2)         DEFAULT NULL,
    drop_total     			DECIMAL(15,2)         DEFAULT NULL,
	current_end_10_14		DECIMAL(15,2)         DEFAULT NULL,
    current_end_15_19   	DECIMAL(15,2)         DEFAULT NULL,
    current_end_20_49   	DECIMAL(15,2)         DEFAULT NULL,
    current_end_total     	DECIMAL(15,2)         DEFAULT NULL,
    new_present_10_14		DECIMAL(15,2)         DEFAULT NULL,
    new_present_15_19   	DECIMAL(15,2)         DEFAULT NULL,
    new_present_20_49   	DECIMAL(15,2)         DEFAULT NULL,
    new_present_total     	DECIMAL(15,2)         DEFAULT NULL,        
    created_at  DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_record_id (record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS a_demand(
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    record_id   INT UNSIGNED          NOT NULL COMMENT 'Parent form / survey record',
    indicator   VARCHAR(500)          NOT NULL COMMENT 'Row label / indicator name',
    age_10_14   DECIMAL(15,2)         DEFAULT NULL,
    age_15_19   DECIMAL(15,2)         DEFAULT NULL,
    age_20_49   DECIMAL(15,2)         DEFAULT NULL,
    total       DECIMAL(15,2)         DEFAULT NULL,
    remarks     TEXT                  DEFAULT NULL,
    created_at  DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_record_id (record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;